### PR TITLE
Fix some issues with completion

### LINKED ISSUE #111: No completion for `hiding`, `as` and `public` in imports

### LINKED ISSUE #118: No completion for keywords

### PR DESCRIPTION
**Pull request by kkarnauk**
Fix #111
Fix #118

### CODE REVIEW

File: src/main/kotlin/com/plugin/frege/completion/FregeCompletionUtil.kt [hunk 1]
```diff
@@ -7,7 +7,6 @@ object FregeCompletionUtil {
     @JvmStatic
     fun shouldComplete(element: PsiElement): Boolean {
         // There are problems with unnecessary completion after numbers/etc
-        // The first condition for optimization
-        return element.text == CompletionUtilCore.DUMMY_IDENTIFIER_TRIMMED
+        return element.text != CompletionUtilCore.DUMMY_IDENTIFIER_TRIMMED
     }
```
Comment (psurkov) [inline src/main/kotlin/com/plugin/frege/completion/FregeCompletionUtil.kt:11]: )))
